---
# Variable setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Enable Gluu service
  command: /sbin/gluu-serverd-{{ gluu_version }} enable

- name: Start Gluu service
  command: /sbin/gluu-serverd-{{ gluu_version }} start
  
- include: gluu-configuration.yml